### ISSUE TITLE
Omitting `identity` causes a panic: value is null

### ISSUE THREAD

**Issue by bak-fts** [upbound/provider-upjet-azapi#103]
### What happened?

Resources without `identity` cause a panic "value is null" to be logged in the controller / provider pod on observe.

This makes it impossible to manage resources which do not accept an identity in their body to be managed by this provider. (Example: https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/managedclusters/maintenanceconfigurations?pivots=deployment-language-terraform)

```
E0602 15:10:40.924520       1 runtime.go:77] Observed a panic: value is null
goroutine 243 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1c72920, 0x88582c0})
        k8s.io/apimachinery@v0.29.1/pkg/util/runtime/runtime.go:75 +0x85
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
        sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:108 +0xb2
panic({0x1c72920?, 0x88582c0?})
        runtime/panic.go:785 +0x132
github.com/hashicorp/go-cty/cty.Value.LengthInt({{{0x887c340?, 0xc0027bab30?}}, {0x0?, 0x0?}})
        github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:989 +0x258
github.com/hashicorp/go-cty/cty.Value.AsValueSlice({{{0x887c340?, 0xc0027bab30?}}, {0x0?, 0x0?}})
        github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:1216 +0x7a
github.com/Azure/terraform-provider-azapi/internal/services.isConfigExist({{{0x887c2d0?, 0xc000520c30?}}, {0x1d38c40?, 0xc0013faed0?}}, {0x2018f01, 0x8})
        github.com/Azure/terraform-provider-azapi@v1.15.0/internal/services/azapi_resource.go:562 +0xad
github.com/Azure/terraform-provider-azapi/internal/services.AzApiResource.func2({0x887b950?, 0xc0010563f0?}, 0xc002384780, {0x1d33780, 0xc000331480})
        github.com/Azure/terraform-provider-azapi@v1.15.0/internal/services/azapi_resource.go:192 +0x5a5
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc00043e780, {0x887b950, 0xc0010563f0}, 0xc0019dd2b0, 0xc000394320, 0x865e208, {0x1d33780, 0xc000331480}, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/schema/schema.go:698 +0x4b4
github.com/crossplane/upjet/pkg/controller.(*terraformPluginSDKExternal).getResourceDataDiff(0xc00077a460, {0x79ed7126c148, 0xc002330008}, {0x887b950, 0xc0010563f0}, 0xc0019dd2b0, 0x0)
        github.com/crossplane/upjet@v1.4.1/pkg/controller/external_tfpluginsdk.go:419 +0xb5
github.com/crossplane/upjet/pkg/controller.(*terraformPluginSDKExternal).Observe(0xc00077a460, {0x887b950, 0xc0010563f0}, {0x889ae68, 0xc002330008})
        github.com/crossplane/upjet@v1.4.1/pkg/controller/external_tfpluginsdk.go:495 +0x525
github.com/crossplane/upjet/pkg/controller.(*terraformPluginSDKAsyncExternal).Observe(0xc0007b50c0, {0x887b950, 0xc0010563f0}, {0x889ae68, 0xc002330008})
        github.com/crossplane/upjet@v1.4.1/pkg/controller/external_async_tfpluginsdk.go:127 +0xc5
github.com/crossplane/crossplane-runtime/pkg/reconciler/managed.(*Reconciler).Reconcile(0xc0001ed400, {0x887b8a8, 0xc000b982a0}, {{{0x0, 0x0}, {0xc0008feb40, 0x2e}}})
        github.com/crossplane/crossplane-runtime@v1.16.0/pkg/reconciler/managed/reconciler.go:914 +0x2110
github.com/crossplane/crossplane-runtime/pkg/ratelimiter.(*Reconciler).Reconcile(0xc000472a00, {0x887b8a8, 0xc000b982a0}, {{{0x0?, 0x5?}, {0xc0008feb40?, 0xc0022ebd10?}}})
        github.com/crossplane/crossplane-runtime@v1.16.0/pkg/ratelimiter/reconciler.go:54 +0x151
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x88824b8?, {0x887b8a8?, 0xc000b982a0?}, {{{0x0?, 0xb?}, {0xc0008feb40?, 0x0?}}})
        sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:119 +0xa5
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00062c640, {0x887b8e0, 0xc0004de4b0}, {0x1e09660, 0xc0006b2520})
        sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:316 +0x39c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00062c640, {0x887b8e0, 0xc0004de4b0})
        sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:266 +0x19d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:227 +0x73
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 130
        sigs.k8s.io/controller-runtime@v0.17.0/pkg/internal/controller/controller.go:223 +0x50c
```

### How can we reproduce it?

Create a resource such as `Microsoft.ContainerService/managedClusters/maintenanceConfigurations` without setting `spec.forProvider.identity` or setting `spec.forProvider.identity` to an empty array.

```yaml
---
apiVersion: resources.azapi.upbound.io/v1beta1
kind: Resource
metadata:
  name: example
  annotations:
    crossplane.io/external-name: {{ $spec.forComposer.resourceGroupId }}/providers/Microsoft.ContainerService/managedClusters/{{ $clusterName }}/maintenanceConfigurations/aksManagedAutoUpgradeSchedule
    gotemplating.fn.crossplane.io/composition-resource-name: ExampleMaintenanceConfiguration
spec:
  forProvider:
    type: Microsoft.ContainerService/managedClusters/maintenanceConfigurations@2025-02-02-preview
    name: aksManagedAutoUpgradeSchedule
    parentId: {{ $spec.forComposer.resourceGroupId }}/providers/Microsoft.ContainerService/managedClusters/{{ $clusterName }}
    schemaValidationEnabled: false
    body: |-
      {
        "properties": {
          "maintenanceWindow": {"durationHours":4,"schedule":{"relativeMonthly":{"dayOfWeek":"Monday","intervalMonths":1,"weekIndex":"First"}},"startTime":"08:00","utcOffset":"+02:00"}
        }
      }
```

### What environment did it happen in?

* provider-upjet-azapi@1.0.0
