### ISSUE TITLE
`ignoreBodyChanges` does nothing

### ISSUE THREAD

**Issue by bak-fts** [upbound/provider-upjet-azapi#11]
### What happened?

When trying to ignore changes via `ignoreBodyChanges`, they are not ignored. This leads to continuous reconciliation of resources which set properties themselves automatically, such as AKS.

The equivalent of `lifecycle.ignore_changes` works fine in Terraform.

### How can we reproduce it?

Consider the following resource (specific resource values omitted).

The AKS cluster keeps being updated by Crossplane, because it does not ignore changes to `properties.addonProfiles.azurepolicy.identity`, which is a field populated by Azure themselves every update cycle.

```yaml
            ---
            apiVersion: resources.azapi.upbound.io/v1beta1
            kind: Resource
            metadata:
              name: example-aks-resource
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: Resource
            spec:
              forProvider:
                type: Microsoft.ContainerService/managedClusters@2024-03-02-preview
                name: example-aks-cluster
                location: switzerlandnorth
                parentId: ...
                schemaValidationEnabled: false
                ignoreBodyChanges:
                  - properties.addonProfiles.azurepolicy.identity
                  - properties.addonProfiles.azureKeyvaultSecretsProvider.identity
                identity:
                  - type: "UserAssigned"
                    identityIds:
                      - ...
                body: |-
                  {
                    "sku": {
                      "name": "Base",
                      "tier": "Free"
                    },

                    "properties": {
                      "kubernetesVersion": "1.31",
                      "dnsPrefix": "test",
                      "supportPlan": "KubernetesOfficial",

                      "agentPoolProfiles": [
                        {
                          "name": "default",
                          "count": 1,
                          "vmSize": "Standard_D2as_v5",
                          "osDiskSizeGB": 127,
                          "osDiskType": "Managed",
                          "vnetSubnetID": ...,
                          "kubeletDiskType": "OS",
                          "maxPods": 31,
                          "type": "VirtualMachineScaleSets",
                          "maxCount": 10,
                          "minCount": 2,
                          "enableAutoScaling": true,
                          "enableEncryptionAtHost": true,
                          "mode": "System",
                          "osType": "Linux",
                          "osSKU": "AzureLinux",
                          "enableFIPS": false,
                          "enableNodePublicIP": false,
                          "availabilityZones": ["1", "2","3"],

                          "nodeLabels": {
                            "workload": "true",
                            "egress_gateway": "false"
                          }
                        }
                      ],

                      "servicePrincipalProfile": {
                        "clientId": "msi"
                      },

                      "addonProfiles": {
                        "azureKeyvaultSecretsProvider": {
                          "enabled": true,

                          "config": {
                            "enableSecretRotation": "true",
                            "rotationPollInterval": "2m"
                          }
                        },

                        "azurepolicy": {
                          "enabled": true
                        }
                      },

                      "nodeResourceGroup": "MC_test-rg_example-aks-cluster_switzerlandnorth",
                      "enableRBAC": true,

                      "securityProfile": {
                        "workloadIdentity": {
                          "enabled": true
                        },
                      },

                      "aadProfile": {
                        "enableAzureRBAC": true,
                        "managed": true,
                        "adminGroupObjectIDs": [...]
                      },

                      "networkProfile": {
                        "networkPlugin": "none",
                        "networkPolicy": "none",
                        "loadBalancerSku": "standard",
                        "serviceCidr": "10.0.1.0/24",
                        "dnsServiceIP": "10.0.1.10",
                        "outboundType": "userDefinedRouting",
                        "podCidr": "10.10.0.0/16",
                        "podCidrs": ["10.10.0.0/16"],

                        "serviceCidrs": [
                          "10.0.1.0/24"
                        ],

                        "ipFamilies": [
                          "IPv4"
                        ],

                        "kubeProxyConfig": {
                          "enabled": false,
                          "mode": "IPVS",

                          "ipvsConfig": {
                            "scheduler": "LeastConnection",
                            "tcpTimeoutSeconds": 900,
                            "tcpFinTimeoutSeconds": 120,
                            "udpTimeoutSeconds": 300
                          }
                        }
                      },

                      "apiServerAccessProfile": {
                        "enablePrivateCluster": true,
                        "privateDNSZone": ...,
                        "enablePrivateClusterPublicFQDN": false
                      },

                      "autoScalerProfile": {
                        "balance-similar-node-groups": "false",
                        "max-node-provision-time": "15m",
                        "scale-down-delay-after-add": "10m",
                        "skip-nodes-with-local-storage": "false",
                        "daemonset-eviction-for-occupied-nodes": true
                      },

                      "autoUpgradeProfile": {
                        "nodeOSUpgradeChannel": "NodeImage",
                        "upgradeChannel": "patch"
                      },

                      "disableLocalAccounts": true,

                      "storageProfile": {
                        "diskCSIDriver": {
                          "enabled": true
                        },

                        "fileCSIDriver": {
                          "enabled": true
                        },

                        "snapshotController": {
                          "enabled": true
                        }
                      },

                      "publicNetworkAccess": "Disabled",
    
                      "oidcIssuerProfile": {
                        "enabled": true
                      },

                      "identityProfile": {
                        "kubeletidentity": {
                          "resourceId": ...,
                        }
                      },

                      "metricsProfile": {
                        "costAnalysis": {
                          "enabled": false
                        }
                      },

                      "controlPlanePluginProfiles": {
                        "azure-monitor-metrics-ccp": {
                          "enableV2": true
                        },

                        "karpenter": {
                          "enableV2": true
                        }
                      }
                    }
                  }
```

### What environment did it happen in?

Crossplane v1.18.2
provider-azapi v1.0.0
